application: distancetotalr
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /results
  script: frontend.app
- url: /static/
  static_dir: static
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /
  static_files: static/index.html
  upload: /static/.*
